name: pytorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - numpy=2.2.5
  - pandas=2.3.2
  - matplotlib=3.10.1
  - pillow=11.2.1
  - tqdm=4.67.1
  - pip
  - pip:
      - diffusers==0.36.0.dev0
      - torch==2.6.0
      - torchvision==0.21.0
      - transformers==4.52.4
      - wandb==0.20.1
      - kornia==0.8.1

